#!/bin/bash

set -e

missing_params(){
	echo 'missings params'
	echo 'indocker image "<command>"'
}

if [ -z "$1" ] || [ -z "$2" ]
then
	missing_params && exit
fi

port_command=""
if [ "$3" ]
then
	port_command="-p $3:$3"
fi

docker run -it $port_command -v $PWD:$PWD $1 sh -c "cd $PWD && $2"
